### ISSUE TITLE
Bug: The demo (index.html) throwing error "Uncaught UnsupportedVersion at versionCheck" 

### ISSUE THREAD

**Issue by limcheekin** [surrealdb/surrealdb.wasm#93]
### Describe the bug

Unable to run the surrealdb.wasm in Chrome browser due to the error above. 

### Steps to reproduce

I clone the latest source from `surrealdb.wasm` repo and run the following commands:
```
pnpm i
make build
pnpm serve
```
Then, I open `http://127.0.0.1:8000/` in the chrome browser, the demo (index.html) is loaded successfully. But when I tried running `await surreal.connect("indxdb://test")` in browser console, it is throwing the following error: 
```
Uncaught UnsupportedVersion
    at versionCheck (http://127.0.0.1:8000/node_modules/surrealdb.js/dist/esm.bundled.js:1:34314)
    at Surreal.connect (http://127.0.0.1:8000/node_modules/surrealdb.js/dist/esm.bundled.js:1:42891)
    at async <anonymous>:1:1
```

### Expected behaviour

It should connect successfully.

### SurrealDB version

surrealdb.wasm v1.0.0-beta.13

### Contact Details

limcheekin@vobject.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by limcheekin** [comment]
Tested and it works in v1.0.0-beta.14.
